config/routes.rb
Rails.application.routes.draw do

  resources :sold_items
  resources :orders, only:[:index, :create, :destroy]
  resources :carts, only:[:index, :create, :destroy]

  resources :activities do
    collection { post :import}
  end
  devise_for :users

  devise_scope :user do
    root :to => 'activities#index'
  end
  resources :users, except:[:index, :new, :create]
	resources :charges, only:[:index, :new, :create]

	namespace :admin do
		resources :users
	end

end

app/models/sold_item.rb
class SoldItem < ApplicationRecord
    belongs_to :user
    belongs_to :activity
    belongs_to :order
end

app/controllers/sold_items_controller.rb
class SoldItemsController < ApplicationController
  before_action :authenticate_user
  before_action :set_sold_item, only: [:show, :edit, :update, :destroy]

  def index
    @sold_items = SoldItem.all
  end

  def show
  end

  def new
    @sold_item = SoldItem.new
  end

  def edit
  end

  def create
    @sold_item = SoldItem.new(sold_item_params)

    respond_to do |format|
      if @sold_item.save
        format.html { redirect_to @sold_item,flash: { success: 'Sold item was successfully created.'} }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @sold_item.update(sold_item_params)
        format.html { redirect_to @sold_item,flash: { success: 'Sold item was successfully updated.'} }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @sold_item.destroy
    respond_to do |format|
      format.html { redirect_to sold_items_url,flash: {success: 'Sold item was successfully destroyed.'} }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sold_item
      @sold_item = SoldItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sold_item_params
      params.fetch(:sold_item, {})
    end
end

app/helpers/sold_items_helper.rb
module SoldItemsHelper
end

app/views/sold_items/_form.html.erb
<%= form_with(model: sold_item, local: true) do |form| %>
  <% if sold_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sold_item.errors.count, "error") %> prohibited this sold_item from being saved:</h2>

      <ul>
      <% sold_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sold_items/edit.html.erb
<h1>Editing Sold Item</h1>

<%= render 'form', sold_item: @sold_item %>

<%= link_to 'Show', @sold_item %> |
<%= link_to 'Back', sold_items_path %>

app/views/sold_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sold Items</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sold_items.each do |sold_item| %>
      <tr>
        <td><%= link_to 'Show', sold_item %></td>
        <td><%= link_to 'Edit', edit_sold_item_path(sold_item) %></td>
        <td><%= link_to 'Destroy', sold_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sold Item', new_sold_item_path %>

app/views/sold_items/new.html.erb
<h1>New Sold Item</h1>

<%= render 'form', sold_item: @sold_item %>

<%= link_to 'Back', sold_items_path %>

app/views/sold_items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sold_item_path(@sold_item) %> |
<%= link_to 'Back', sold_items_path %>