config/routes.rb
Rails.application.routes.draw do

  resources :sold_items
  resources :orders, only:[:index, :create, :destroy]
  resources :carts, only:[:index, :create, :destroy]

  resources :activities do
    collection { post :import}
  end
  devise_for :users

  devise_scope :user do
    root :to => 'activities#index'
  end
  resources :users, except:[:index, :new, :create]
	resources :charges, only:[:index, :new, :create]

	namespace :admin do
		resources :users
	end

end

app/models/cart.rb
class Cart < ApplicationRecord

    belongs_to :user
    belongs_to :activity

    def self.amount(items)
        amount = 0
        items.each do |item|
            amount += item.activity.price
        end
        return amount
    end

    def self.destro(user_id)
        @carts_user = Cart.where(user_id: user_id)
        @carts_user.each do |cart|
            cart.destroy
        end
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user
  before_action :set_cart, only: [:destroy]
  before_action :carts_user, only: [:index, :destro]

  def index
   # @carts_user = Cart.where(user_id: current_user.id)
    @amount = Cart.amount(@carts_user)
  end

  def create
    @cart = Cart.new(cart_params)
    @cart.activity_id = Activity.find(params[:activity_id]).id
    @cart.user_id = current_user.id

    if @cart.save
    redirect_to activities_path, flash: { success: 'Activity added to cart'}
    else
      render :new
    end
  end

  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, flash: { success: 'Activity removed from cart'} }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    def carts_user
      @carts_user = Cart.where(user_id: current_user.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
<% if cart.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

  <ul>
    <% cart.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

  <h1 class="title_cart"> My cart </h1>

<div class="container cart_Table">
  <div class="tabl-cart">
    <table class="table ">
      <thead>
        <tr>
          <th scope="col">Product</th>
          <th scope="col">Title</th>
          <th scope="col">Quantity</th>
          <th scope="col">Price</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
      <tbody>
        <% @carts_user.each do |cart| %>
        <tr>
          <td><%= image_tag cart.activity.image_url, class:"img-50" %></td>
          <td class="cart_title"><%=cart.activity.title%></td>
          <td><%= 1%></td>
          <td><%= cart.activity.price  %> $</td>
          <td><%= link_to  cart, method: :delete, data: { confirm: 'Are you sure?' } do%> <i class="fas fa-trash"></i>
            <%end%></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row justify-content-center">
  <%= form_tag charges_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <span>Amount: <%= @amount %>$</span>
      </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="A month's subscription"
            data-amount= <%= @amount*100 %>
            data-locale="auto"></script>
  <% end %>
  </div>
</div>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>