config/routes.rb
Rails.application.routes.draw do

  resources :sold_items
  resources :orders, only:[:index, :create, :destroy]
  resources :carts, only:[:index, :create, :destroy]

  resources :activities do
    collection { post :import}
  end
  devise_for :users

  devise_scope :user do
    root :to => 'activities#index'
  end
  resources :users, except:[:index, :new, :create]
	resources :charges, only:[:index, :new, :create]

	namespace :admin do
		resources :users
	end

end

app/models/activity.rb
class Activity < ApplicationRecord

    validates :title, presence: true, length: {in: 5..140}
    validates :description, presence: true, length: {in: 20..1000}
    validates :price, presence: true
    validates :image_url, presence: true, uniqueness: true
    
    has_many :carts
    has_many :users, through: :carts
    has_many :sold_items

		has_one_attached :illustration

    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            Activity.create! row.to_hash
        end
    end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin, except: [:index, :show]

  def index
    @activities = Activity.all
  end

  def show
  end

  def new
    @activity = Activity.new
  end

  def edit
  end

  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, flash: {success: 'Activity was successfully created.'} }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity,flash: { success: 'Activity was successfully updated.'} }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url,flash: { success: 'Activity was successfully destroyed.'} }
    end
  end

  def import
    Activity.import(params[:file])
    redirect_to activities_path, flash: {info: "Activities Added"}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.fetch(:activity, {}).permit(:title, :description, :price, :image_url)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_card.html.erb
<div class="row">
  <div class="card m-2" style="width: 16rem;">
    <%= image_tag activity.illustration, class:"img_card" %>
    <p class="price"><%=activity.price%> $</p>
    <h5 class="card-title title_act"><%= activity.title %></h5>
    <br>
    <div class="row button_row_act">
      <%= link_to 'Show', activity, class: "btn btn-primary button_act" %>
	
		<% if current_user then	 %>
			<% if current_user.is_admin then %>
				<%= link_to 'Edit', edit_activity_path(activity), class: "btn btn-primary button_act" %>
				<%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-primary" %>
			<% end %>
		<% end %>
    </div>
    <br>
  </div>
</div>

app/views/activities/_form.html.erb
<div class="container edit_user_form">
  <% if @activity.errors.any? %>
    <div class="alert alert-danger-form">
    <div id="error_explanation">
    <p> <%= pluralize(@activity.errors.count, "error") %> prohibited this event from being saved:</p>   
        <ul>
        <% @activity.errors.full_messages.each do |message| %>
            <li><%= message %></li>              
        <% end %>
        </ul>
</div>
    </div>
  <% end %>
  <%= form_for @activity do |f| %>

    <div class="form-group">
      <%= f.label :title, "Title" %>
      <em class="sm">  ... minimum 6 characters</em> <br />
      <%= f.text_field :title, autocomplete: "title", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description, "Description" %>
      <em class="sm">  ... minimum 20 caracharacters</em> <br />
      <%= f.text_field :description, autocomplete: "description", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :price, "Price" %>
      <em class="sm">  ... between 1 and 1000</em> <br />
      <%= f.number_field :price, autocomplete: "price", class: "form-control" %>
    </div>
      <div class="form-group">
      <%= f.label :image_url, "Image link" %>
      <em class="sm">  ... url of your image</em> <br />
      <%= f.text_field :image_url, autocomplete: "image_url", class: "form-control" %>
    </div>
    <div class="actions mt-5 mb-4">
      <%= f.submit "Add this activity", class:"btn btn-md btn-primary btn-block text-uppercase" %>
    </div>

  <% end %>
</div>

app/views/activities/_showForm.html.erb
<div class="container-fluid">
        <div class="card m-3">
      
          <!-- <h3 class="card-header">Activity [<%= @activity.id%>]</h3>
       -->
      
          <div class="card-body showCard">
      
      
            <h1 class="card-title showActivityTitle"><%=@activity.title%></h1>
            <h6 class="card-subtitle text-muted"></h6>
            <%= image_tag @activity.illustration, class:"pic1",  alt:"Card image" %>   
            <p id="notice"><%= notice %></p>
             <%=@activity.description%>
              <%= button_to 'Add to Cart', carts_path(:activity_id => @activity.id), method: :post, class: "mr-4"%>
      
          </div>
        </div>
      </div>
      
      
      
      

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>activities</title>
</head>
<body>
  
  <div class="jumpo">
    <%= render "layouts/jumpotron" %>
  </div>
  <div class="activities">
    <h1>Activities</h1>
    <% if current_user then %>
		<% if current_user.is_admin then %>
    <%= link_to 'New Activity', new_activity_path, class: "btn btn-primary" %>
		<% end %>
    <% end %>
    
    <% if current_user then %>
		<% if current_user.is_admin then %>
    <%= link_to 'Panel admin', admin_users_path, class: "btn btn-primary" %>
		<% end %>
    <% end %>
    
    <div class="card-deck">
      <% for activity in @activities do %>
      <%= render partial: "card", locals: {activity: activity} %>
      <% end  %>
    </div>
  </div>
  
  
  <br>
  <br>
  <br>
  <div id="discover_seville">
    <div class="container text-light">
      <br>
      <br>
      <br>
      <center><h1 class="videoTitle">discover Sevilla!</h1></center>
      <br>
      <iframe href="#sevilla" width="560" height="315" src="https://www.youtube.com/embed/KXsE0qVJp_s" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      
      <br>
      <br>
      <br>
      
    </div>
    
  </div>
</body>
</html>
  

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<div class="row justify-content-center">
    <div class="col m-3">
        <!-- CSV Uploader -->
        <h3> Import activities </h3>
        <%= form_tag import_activities_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= submit_tag "Upload activities" %>
        <%end %>
    </div>
</div>

app/views/activities/show.html.erb
<div class="container-fluid">
  <div class="card m-3">

    <!-- <h3 class="card-header">Activity [<%= @activity.id%>]</h3>
 -->

    <div class="card-body showCard">


      <h1 class="card-title showActivityTitle"><%=@activity.title%></h1>
      <h6 class="card-subtitle text-muted"></h6>
      <%= image_tag @activity.illustration, class:"pic1",  alt:"Card image" %>   
      <p id="notice"><%= notice %></p>
       <%=@activity.description%>
        <%= button_to 'Add to Cart', carts_path(:activity_id => @activity.id), method: :post, class: "mr-4"%>

    </div>
  </div>
</div>