config/routes.rb
Rails.application.routes.draw do

  resources :sold_items
  resources :orders, only:[:index, :create, :destroy]
  resources :carts, only:[:index, :create, :destroy]

  resources :activities do
    collection { post :import}
  end
  devise_for :users

  devise_scope :user do
    root :to => 'activities#index'
  end
  resources :users, except:[:index, :new, :create]
	resources :charges, only:[:index, :new, :create]

	namespace :admin do
		resources :users
	end

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="page-footer">
  <!-- Footer Elements -->
    <div class="container">
    <!-- Grid row-->
      <div class="row">
      <!-- Grid column -->
        <div class="col-md-12 py-5">
          <div class="mb-5 flex-center">
            <!-- Facebook -->
            <a class="fb-ic"><i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i></a>
            <!-- Twitter -->
            <a class="tw-ic"><i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i></a>
            <!-- Google +-->
            <a class="gplus-ic"><i class="fab fa-google-plus-g fa-lg white-text mr-md-5 mr-3 fa-2x"> </i></a>
            <!--Linkedin -->
            <a class="li-ic"><i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i></a>
            <!--Instagram-->
            <a class="ins-ic"><i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i></a>
            <!--Pinterest-->
            <a class="pin-ic"><i class="fab fa-pinterest fa-lg white-text fa-2x"> </i></a>
          </div>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row-->
  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3"> © 2019 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/"> TravelShop</a>
  </div>
  <!-- Copyright -->


<!-- Footer -->
</div>

</footer>

app/views/layouts/_jumpotron.html.erb
<div class="jumbotron img_jumpo">
  <br>
  <h1 class="display-4">Travel Shop</h1>
  <br>
  <hr class="my-4">
<br>
<br>
  <p class="lead">
    <a class="btn btn-primary btn-lg" role="button">to nowhere</a>
  </p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary navbarre">
  <a class="navbar-brand" href="/"><i class="fas fa-globe-americas fa-3x"></i></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  ​
  <div class="collapse navbar-collapse nav" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item cart">
        <% if user_signed_in? %>
          <%= link_to carts_path,class: 'nav-link' do %><span class="titnav">Cart <i class="fas fa-shopping-cart"></i></span><%end%>
        <% end %>
      </li><% if user_signed_in? %>
      <li class="nav-item dropdown profile">  
       
          <a class="nav-link dropdown-toggle toggle navTitle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
             aria-haspopup="true" aria-expanded="false">
             <span class="titnav"> profile</span>
          </a>  
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
     
        <%= link_to "Profile", user_path(current_user.id), class:"dropdown-item" %>
          <%= link_to "edit", edit_user_path(current_user.id), class:"dropdown-item" %>
         
          
          
          </div>
          </li>
      </li><%end%>
       
      <li class="nav-item dropdown loginLogout">
        <a class="nav-link dropdown-toggle navTitle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
           <span class="titnav"> Login/out</span>
        </a>
        <div class="dropdown-menu logaout" aria-labelledby="navbarDropdown">
          <% if user_signed_in?%>
            <%= link_to('Logout',destroy_user_session_path, method: :delete,class: 'dropdown-item') %>
          <% else %>
            <style type="text/css">
          .loginLogout { margin-left: 150vh;}
            </style>
            <%= link_to('Sign Up', new_user_registration_path,class:'dropdown-item') %>
            <%= link_to('Login', new_user_session_path,class: 'dropdown-item')%>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_userButton.html.erb
<%= image_tag 'userbutton.png', class: 'userButton'%>

app/views/layouts/application.html.erb
<!doctype html>


<head>
  <title>TravelShop</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://kit.fontawesome.com/71edf01ac1.js" crossorigin="anonymous"></script>


  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.4.0/minty/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-fxjtfye5lBqRzUYAuu3mYLPl6DvTteQimjr/VmCTPDmm63nysPfCpyWp4084CzY2" crossorigin="anonymous">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%=render "layouts/navbar" %>
  <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %><button type="button" class="close" data-dismiss="alert"
      aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button></div>
  <% end %>

  <%= yield %>




  <%= render "layouts/footer" %>
</body>

</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>